// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/note.dart';
import 'data/models/note_chunk.dart';
import 'data/models/note_edge.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3846300818630381873),
    name: 'Note',
    lastPropertyId: const obx_int.IdUid(7, 8927346510928374653),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3333077260101021428),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2553925027823518564),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8144287631666071852),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4403534186943646193),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2894548097151026698),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6738492019384756102),
        name: 'noteEmbedding',
        type: 28,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8927346510928374653),
        name: 'attachmentsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6380278326908799177),
    name: 'NoteChunk',
    lastPropertyId: const obx_int.IdUid(8, 6123456789012345670),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4229953832564358611),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2409289267553996144),
        name: 'noteId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4373863693707044096),
        relationField: 'note',
        relationTarget: 'Note',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5052416955317697121),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1991467620914032960),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7288767360520539162),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 1720658735915024289),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4545782700273148906),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4498683549219253186),
        name: 'contextHeader',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6123456789012345670),
        name: 'chunkMetadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7283746510293847561),
    name: 'NoteEdge',
    lastPropertyId: const obx_int.IdUid(4, 8374650192837465109),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1029384756102938475),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2938475610293847561),
        name: 'noteIdA',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3847561029384756102),
        name: 'noteIdB',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8374650192837465109),
        name: 'similarityScore',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7283746510293847561),
    lastIndexId: const obx_int.IdUid(2, 1720658735915024289),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 2,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Note: obx_int.EntityDefinition<Note>(
      model: _entities[0],
      toOneRelations: (Note object) => [],
      toManyRelations: (Note object) => {},
      getId: (Note object) => object.id,
      setId: (Note object, int id) {
        object.id = id;
      },
      objectToFB: (Note object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        final noteEmbeddingOffset = fbb.writeListFloat32(object.noteEmbedding);
        final attachmentsJsonOffset = fbb.writeString(object.attachmentsJson);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, bodyOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(5, noteEmbeddingOffset);
        fbb.addOffset(6, attachmentsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final noteEmbeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final attachmentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = Note(
          id: idParam,
          title: titleParam,
          body: bodyParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          noteEmbedding: noteEmbeddingParam,
          attachmentsJson: attachmentsJsonParam,
        );

        return object;
      },
    ),
    NoteChunk: obx_int.EntityDefinition<NoteChunk>(
      model: _entities[1],
      toOneRelations: (NoteChunk object) => [object.note],
      toManyRelations: (NoteChunk object) => {},
      getId: (NoteChunk object) => object.id,
      setId: (NoteChunk object, int id) {
        object.id = id;
      },
      objectToFB: (NoteChunk object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        final contextHeaderOffset = fbb.writeString(object.contextHeader);
        final chunkMetadataJsonOffset = fbb.writeString(
          object.chunkMetadataJson,
        );
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.note.targetId);
        fbb.addInt64(2, object.chunkIndex);
        fbb.addOffset(3, textOffset);
        fbb.addOffset(4, embeddingOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(6, contextHeaderOffset);
        fbb.addOffset(7, chunkMetadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final chunkIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contextHeaderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final chunkMetadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = NoteChunk(
          id: idParam,
          chunkIndex: chunkIndexParam,
          text: textParam,
          contextHeader: contextHeaderParam,
          chunkMetadataJson: chunkMetadataJsonParam,
          embedding: embeddingParam,
          createdAt: createdAtParam,
        );
        object.note.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.note.attach(store);
        return object;
      },
    ),
    NoteEdge: obx_int.EntityDefinition<NoteEdge>(
      model: _entities[2],
      toOneRelations: (NoteEdge object) => [],
      toManyRelations: (NoteEdge object) => {},
      getId: (NoteEdge object) => object.id,
      setId: (NoteEdge object, int id) {
        object.id = id;
      },
      objectToFB: (NoteEdge object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.noteIdA);
        fbb.addInt64(2, object.noteIdB);
        fbb.addFloat64(3, object.similarityScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final noteIdAParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final noteIdBParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final similarityScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = NoteEdge(
          id: idParam,
          noteIdA: noteIdAParam,
          noteIdB: noteIdBParam,
          similarityScore: similarityScoreParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.id].
  static final id = obx.QueryIntegerProperty<Note>(_entities[0].properties[0]);

  /// See [Note.title].
  static final title = obx.QueryStringProperty<Note>(
    _entities[0].properties[1],
  );

  /// See [Note.body].
  static final body = obx.QueryStringProperty<Note>(_entities[0].properties[2]);

  /// See [Note.createdAt].
  static final createdAt = obx.QueryDateProperty<Note>(
    _entities[0].properties[3],
  );

  /// See [Note.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Note>(
    _entities[0].properties[4],
  );

  /// See [Note.noteEmbedding].
  static final noteEmbedding = obx.QueryDoubleVectorProperty<Note>(
    _entities[0].properties[5],
  );

  /// See [Note.attachmentsJson].
  static final attachmentsJson = obx.QueryStringProperty<Note>(
    _entities[0].properties[6],
  );
}

/// [NoteChunk] entity fields to define ObjectBox queries.
class NoteChunk_ {
  /// See [NoteChunk.id].
  static final id = obx.QueryIntegerProperty<NoteChunk>(
    _entities[1].properties[0],
  );

  /// See [NoteChunk.note].
  static final note = obx.QueryRelationToOne<NoteChunk, Note>(
    _entities[1].properties[1],
  );

  /// See [NoteChunk.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<NoteChunk>(
    _entities[1].properties[2],
  );

  /// See [NoteChunk.text].
  static final text = obx.QueryStringProperty<NoteChunk>(
    _entities[1].properties[3],
  );

  /// See [NoteChunk.embedding].
  static final embedding = obx.QueryHnswProperty<NoteChunk>(
    _entities[1].properties[4],
  );

  /// See [NoteChunk.createdAt].
  static final createdAt = obx.QueryDateProperty<NoteChunk>(
    _entities[1].properties[5],
  );

  /// See [NoteChunk.contextHeader].
  static final contextHeader = obx.QueryStringProperty<NoteChunk>(
    _entities[1].properties[6],
  );

  /// See [NoteChunk.chunkMetadataJson].
  static final chunkMetadataJson = obx.QueryStringProperty<NoteChunk>(
    _entities[1].properties[7],
  );
}

/// [NoteEdge] entity fields to define ObjectBox queries.
class NoteEdge_ {
  /// See [NoteEdge.id].
  static final id = obx.QueryIntegerProperty<NoteEdge>(
    _entities[2].properties[0],
  );

  /// See [NoteEdge.noteIdA].
  static final noteIdA = obx.QueryIntegerProperty<NoteEdge>(
    _entities[2].properties[1],
  );

  /// See [NoteEdge.noteIdB].
  static final noteIdB = obx.QueryIntegerProperty<NoteEdge>(
    _entities[2].properties[2],
  );

  /// See [NoteEdge.similarityScore].
  static final similarityScore = obx.QueryDoubleProperty<NoteEdge>(
    _entities[2].properties[3],
  );
}
